/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package creatorxml_200924451;
import static com.sun.media.jfxmediaimpl.MediaUtils.error;
import static com.sun.org.apache.xalan.internal.xsltc.compiler.sym.error;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.PrintWriter;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
//import proyectoc2_200924451.estructura.Estructura_Lienzo;
//import proyectoc2_200924451.estructura.Nodo;
//import proyectoc2_200924451.identificadores.ObtieneSimbolos;
//import proyectoc2_200924451.javacc.ParseException;
//import proyectoc2_200924451.javacc.estructura;
//import static proyectoc2_200924451.texto.contenido;
//import static proyectoc2_200924451.texto.contenido2;
/**
 *
 * @author Emerson
 */
public class pantallainicial extends javax.swing.JFrame {
    private JTextArea contenido =  null;
    private JFileChooser file;
    private File datos;
    public String NamFiles;
    int contador = 0;
//    areapintar area;
//     public String EnderecoArquivo,EnderecoTemporario,bufferIn;
//        public String data ;
//        public int resultadoJanelas;
//        static Scanner calc= null;
int h=0;
//
//hilo g;
      
        
    /**
     * Creates new form pantallainicial
     */
    public pantallainicial() {
        initComponents();
	//contadorlineas(this.jTextArea1, this.jTextPane2, this.jScrollPane1);
    }
	
	 public void contadorlineas(final JTextArea texto, final JTextPane linea, JScrollPane scroll) {

        texto.getDocument().addDocumentListener(new DocumentListener() {
            public String getText() {
                int posicion = texto.getDocument().getLength();
                javax.swing.text.Element ruta = texto.getDocument().getDefaultRootElement();
                String text = "1" + System.getProperty("line.separator");
                for (int i = 2; i < ruta.getElementIndex(posicion) + 2; i++) {
                    text += i + System.getProperty("line.separator");
                }
                return text;
            }
            
            @Override
            public void changedUpdate(DocumentEvent de) {
                linea.setText(getText());
            }

            @Override
            public void insertUpdate(DocumentEvent de) {
                linea.setText(getText());
            }

            @Override
            public void removeUpdate(DocumentEvent de) {
                linea.setText(getText());
            }
        });
        scroll.getViewport().add(texto);
        scroll.setRowHeaderView(linea);

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        contenido2 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();

        jMenuItem8.setText("jMenuItem8");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem9.setText("jMenuItem9");

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proyecto Creator XML");
        setBackground(new java.awt.Color(0, 153, 255));

        jTabbedPane1.setBackground(new java.awt.Color(0, 153, 255));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setName(""); // NOI18N

        jLabel1.setText("Resultado");

        contenido2.setColumns(20);
        contenido2.setRows(5);
        jScrollPane1.setViewportView(contenido2);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jMenu2.setText("Archivo");

        jMenuItem4.setText("Abrir Archivo");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Guardar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Guardar Como");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuBar1.add(jMenu2);

        jMenu1.setText("Pestaña");

        jMenuItem1.setText("Pestaña Nueva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Compilacion");

        jMenuItem10.setText("Compilar Archivo");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Continuar");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem15.setText("Tabla de Simbolos");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem15);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Errores");

        jMenuItem16.setText("Ver Errores");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem16);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
this.getContentPane().setLayout( new BorderLayout() );
        JPanel tabA = new JPanel();
        JTextPane jTextPane2 = new JTextPane();
        tabA.setPreferredSize( new Dimension(100,100) );
        tabA.setLayout( new BorderLayout() );  
        contenido = new JTextArea();
        JScrollPane scroll = new JScrollPane(contenido);
        ///
        contenido.setColumns(20);
        contenido.setRows(5);
        scroll.setViewportView(contenido);
        //
        jTextPane2.setForeground(new java.awt.Color(0, 102, 153));
        jTextPane2.setEnabled(false);
        scroll.setViewportView(jTextPane2);
        //
        contadorlineas(contenido, jTextPane2,  scroll);
        //
        tabA.add(scroll, BorderLayout.CENTER);              
        contador = contador +1;
        this.jTabbedPane1.addTab("Pestaña "+String.valueOf(contador), tabA);     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

        private String AbrirArchivo(){
        String aux = ""; 
        String tex = "";
        contenido.setText(" ");
        try {
            //LLAMAMOS EL MÈTODO QUE PERMITE CARGAR LA VENTANA
            file = new JFileChooser();
            file.showOpenDialog(this);
            file.setDialogTitle("Abrir Documento...");
            //ABRIMOS EL ARCHIVO SELECIONADO
            datos = file.getSelectedFile();
            //OBTENEMOS LA RUTA DEL ARCHIVO
            NamFiles = datos.getPath();
            System.out.println("*****"+NamFiles);
            //RECORREMOS EL ARCHIVO, LO LEEMOS PARA PASARLO AL AREA DE TEXTO
            if(datos!=null){
                FileReader archivos = new FileReader(datos);
                BufferedReader lee = new BufferedReader(archivos);
                while((aux=lee.readLine())!=null){
                    tex+= aux + "\n";
                    System.out.println(tex);
                    contenido.setText(tex);
                }
                lee.close();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex +"" + "\nNo se ha encontrado el Archivo", "ADVERTENCIA!!!", JOptionPane.WARNING_MESSAGE);
        }
        //EL TEXTO SE ALMACENA EN EL JTEXTAREA
        return contenido.getText(); 
    }
        
    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed

        AbrirArchivo();

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

      private void GuardarComo(){
        try {
            file = new JFileChooser(System.getProperty("user.dir"));
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("txt", ".txt");
            file.setFileFilter(filtro);
            file.showSaveDialog(contenido);
            String fichero = file.getSelectedFile().toString();
            System.out.println("/////"+fichero);
            String fname = fichero + ".txt";
            datos = new File(fname);
            FileWriter fw = new FileWriter(datos);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(contenido.getText());
            bw.close();
            JOptionPane.showMessageDialog(null, "El Archivo se ha almacenado Correctamente", "Información",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Su Archivo no se ha Almacenado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed

        Guardar();
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
GuardarComo();        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void Analise() throws IOException{
                
//                 EnderecoTemporario =  System.getProperty("java.io.tmpdir")+"temp.txt";
//                 File arquivo = new File(EnderecoTemporario);  
//                 FileWriter fw = new FileWriter(arquivo);  
//                 BufferedWriter bw = new BufferedWriter(fw);      
//                 bw.write(contenido.getText());  
//                 bw.flush();  
//                 bw.close(); 
//                                            //EnderecoTemporario
//                String nomeArq = new String (contenido.getText());
//                Scanner lex = new Scanner(new FileInputStream(nomeArq));
//                String args[] = null;
//                try {
//          
//                lex.processa(); //processamento dos lexemas 
////lex.INIT();
//
//}
//
//catch (Exception e)
//{
//JOptionPane.showMessageDialog(null, "Analise Sintaxica NOT OK");
//System.out.println("Erro de Token.");
////System.out.println(e.getMessage()+"MAIS nadaaaaaa");
//e.printStackTrace();
//}
//catch (Error e)
//{
//System.out.println(e.getMessage());//Mensagem de erro léxico (em ingles) mostrando linha e coluna
//} 
                 
        }
    
    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
    
    
      
            //Lienzo lienzo = Estructura_Lienzo.analizar(contenido.getText());
            //TablaSimbolos tab = new ObtieneSimbolos();
            
      
           // tab.generar(lienzo);
       
            
            //System.out.println(tab.toString());
          
            
//            try {
//            estructura sc = new estructura(new java.io.StringReader(contenido.getText()));
//            sc.Empezar();
//            area = new areapintar(); 
//            } catch (ParseException ex) {
//            Logger.getLogger(pantallainicial.class.getName()).log(Level.SEVERE, null, ex);
//            contenido2.setText("error in expression.\n"+ ex.getMessage());
//            }
//            
//            
    
           
        
        
      
                
                
                      
        
  
              
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    
    public void error() throws Exception{
    
//    try
//                {
//                Estructura_Lienzo lienzo = Estructura_Lienzo.analizar(contenido.getText());
//                ObtieneSimbolos tab = new ObtieneSimbolos();
//                tab.generar(lienzo);
//                System.out.println(tab.toString());
//
//                estructura sc = new estructura(new java.io.StringReader(contenido.getText()));
//                sc.Empezar();
//                area = new areapintar(); 
//            
//                }
//                catch (Exception e)
//                {
//                  contenido2.setText("error in expression.\n"+ e.getMessage());
//                }
    
    }
    
    public void debug(int valorLinea, String Cad, JTextArea ARojo){
     // String texto = "Esto es un ejemplo de un texto\nseparado por saltos de linea\ncomo se puede apreciar.";
//       String texto = contenido.getText();   
//       contador = contenido.getLineCount();
        //System.err.println(valorLinea + "/////////");
    // JOptionPane.showMessageDialog(rootPane, "Fin de Debug");
        for (int i = 0; i < valorLinea; i++) {
         
       String [] lineas = (Cad.trim()).split("\n");
           ARojo.append("Linea"+ i+ ":"+ lineas[i]+"\n");
            ARojo.setForeground(Color.GREEN);
            System.out.println("Linea"+ i+ ":"+ lineas[i]+"\n");
            JOptionPane.showMessageDialog(rootPane, lineas[i]);
            
          //  System.out.println("Linea "+i+ ": "+lineas[i]);
             contenido2.setText("hola " + i);
        }
   
    
    }
    
    
    
    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed

          // String texto = "Esto es un ejemplo de un texto\nseparado por saltos de linea\ncomo se puede apreciar.";
       String texto = contenido.getText();   
       contador = contenido.getLineCount();
        System.err.println(contador + "/////////");
       if(contenido.getLineCount()==h )
       {
           JOptionPane.showMessageDialog(rootPane, "Fin de Debug");
       } else {
             //  JOptionPane.showMessageDialog(rootPane, "Que siga el entierro");
			 //String [] lineas = (Cad.trim()).split("\n");
               String [] lineas = (texto.trim()).split("\n");
        System.out.println("Texto original:\n"+texto);
        System.out.println("Texto modificado:\n");
        //for(int i=0;i<lineas.length;i++){
        
           
           contenido2.append("Linea"+ h+ ":"+ lineas[h]+"\n");
          
           // contenido2.setText("Linea"+ i+ ":"+ lineas[i]);
            contenido2.setForeground(Color.red);
            
           // System.out.println("Linea "+h+ ": "+lineas[h]);
              h++;
       
               }

        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem11ActionPerformed

   
    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
    
//    Estructura_Lienzo lienzo = Estructura_Lienzo.analizar(contenido.getText());
//            ObtieneSimbolos tab = new ObtieneSimbolos();
//        try {
//            tab.generar(lienzo);
//        }catch(Exception e){
//        System.out.println(e);
//        } 
//        
//        try {
//     File Tabla = new File ("C:\\Users\\Emerson\\Documents\\NetBeansProjects\\ProyectoC2_200924451\\src\\proyectoc2_200924451\\creacion\\Tabla.html");
//     Desktop.getDesktop().open(Tabla);
//}catch (IOException ex) {}
//            
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    
    
    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed

        java.util.Date fecha = new Date();
System.out.println (fecha);

        
   
File archivo = new File("D:\\Errores.html");
    	BufferedWriter salida;
    	try 
    	{
            salida = new BufferedWriter(new FileWriter(archivo));
            salida.write("<html>");
            salida.write("<head>");
            salida.write("</head>");
            salida.write("<body background=\"C:\\Users\\Emerson\\Documents\\NetBeansProjects\\ProyectoC2_200924451\\src\\proyectoc2_200924451\\fondo\\fondo.jpg\">");
            salida.write("<h1>");
              salida.write("<center>");
            salida.write("Tabla de Errores");
              salida.write("</center>");
            salida.write("</h1>");
            salida.write("<hr>");
            salida.write("<table border=\"2px\">");
            salida.write("<tr>");
            salida.write("<td>");
            salida.write("<label>");
            salida.write("Error");
        //    salida.write("Fecha:" +fecha+ "\n" +"<br>"+"Errores:"+"\n"+contenido2.getText());
            salida.write("</label>");
            salida.write("</td>");
            salida.write("</tr>");
            salida.write("</table>");
           
            salida.write("<table border=\"2px\">");
            salida.write("<tr>");
            salida.write("<td>");
            salida.write("<label>");
           // salida.write("Error");
            salida.write("Fecha:" +fecha+ "\n" +"<br>"+"Errores:"+"\n"+contenido2.getText());
            salida.write("</label>");
            salida.write("</td>");
            salida.write("</tr>");
            salida.write("</table>");
            
            salida.write("</body>");
            salida.write("</html>");
            salida.close();
            }           
            
    	catch (IOException ex)
    	{
    		
    	}
    try {
     File Tabla = new File ("D:\\Errores.html");
     Desktop.getDesktop().open(Tabla);
}catch (IOException ex) {}
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    
    
    
    public void recorrer_arbol(){
//        Estructura_Lienzo lienzo = Estructura_Lienzo.analizar(contenido.getText());
//       
//        for (int i = 0; i < lienzo.getContenido().size(); i++) {
//            
//           System.out.println("\t\tInicio de Arbol");
//           System.out.println("Nombre:\t"+lienzo.getNombre() + lienzo.getContenido().toArray());
//           System.out.println("Nombre:\t"+ lienzo.getExtendes() );
//           
//           
//                    }
           
         
        }
                        
    
    
      private void Guardar(){
        try {
            //Guardamos el archivo y le damos formato directamente
            if(datos != null){
                datos = file.getSelectedFile();
                FileWriter fil = new FileWriter(datos);
                BufferedWriter BW = new BufferedWriter(fil);
                PrintWriter PW = new PrintWriter(BW);
                PW.print(contenido.getText());
                PW.close();
                contenido.setText("");
                JOptionPane.showMessageDialog(null, "El Archivo se ha almacenado Correctamente", "Información",JOptionPane.INFORMATION_MESSAGE);
            }else{
                Guardar();
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Su Archivo no se ha Almacenado", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallainicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea contenido2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
